# This rule is not used by the project kb-test itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over example.com.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kb-test
    app.kubernetes.io/managed-by: kustomize
  name: busybox-admin-role
rules:
- apiGroups:
  - example.com.my.domain
  resources:
  - busyboxes
  verbs:
  - '*'
- apiGroups:
  - example.com.my.domain
  resources:
  - busyboxes/status
  verbs:
  - get
